// Ключи всех текстур (раздел 7.3.2). Чтобы заменить процедурный арт рисованным,
// достаточно загрузить PNG под теми же ключами — код сцен не меняется.

export const SPR = {
  coin: 'coin',
  coinShine: 'coin.shine',
  shadow: 'shadow',
  glint: 'glint',
  sparkle: 'sparkle',
  dot: 'dot',
  softDot: 'dot.soft',
  ring: 'ring',
  pedestal: 'pedestal',
  gem: { ruby: 'gem.ruby', emerald: 'gem.emerald', sapphire: 'gem.sapphire' },
  halo: { ruby: 'halo.ruby', emerald: 'halo.emerald', sapphire: 'halo.sapphire' },
  column: ['col.0', 'col.1', 'col.2'],
  rubble: ['rubble.0', 'rubble.1', 'rubble.2'],
  head: ['head.0', 'head.1'],
  hero: {
    bootB: 'hero.bootB',
    bootF: 'hero.bootF',
    legB: 'hero.legB',
    legF: 'hero.legF',
    torso: 'hero.torso',
    armB: 'hero.armB',
    armF: 'hero.armF',
    head: 'hero.head',
    eyes: 'hero.eyes',
    eyesClosed: 'hero.eyes.closed',
    eyesFront: 'hero.eyes.front',
    eyesBack: 'hero.eyes.back',
    browsNeutral: 'hero.brows.neutral',
    browsWorried: 'hero.brows.worried',
    browsStrain: 'hero.brows.strain',
    browsHappy: 'hero.brows.happy',
    mouthSmile: 'hero.mouth.smile',
    mouthOpen: 'hero.mouth.open',
    mouthFlat: 'hero.mouth.flat',
    mouthGrit: 'hero.mouth.grit',
    hat: 'hero.hat',
    scarf: 'hero.scarf',
    scarfTail: 'hero.scarfTail',
    lantern: 'hero.lantern',
    bag: ['hero.bag.0', 'hero.bag.1', 'hero.bag.2', 'hero.bag.3'],
    sweat: 'hero.sweat',
  },
  torchHolder: 'torch.holder',
  flames: ['flame.0', 'flame.1', 'flame.2', 'flame.3', 'flame.4', 'flame.5'],
  ember: 'ember',
  door: {
    slab: 'door.slab',
    frameL: 'door.frameL',
    frameR: 'door.frameR',
    lintel: 'door.lintel',
    gear: 'door.gear',
    chain: 'door.chain',
    sky: 'door.sky',
    skyLate: 'door.sky.late',
    beam: 'door.beam',
    rays: 'door.rays',
  },
  hourglass: {
    frame: 'hourglass.frame',
    sand: 'hourglass.sand',
    glass: 'hourglass.glass',
  },
  sandStream: 'sand.stream',
  sandGrain: 'sand.grain',
  dunes: ['dune.0', 'dune.1', 'dune.2'],
  puff: 'puff',
  crack: 'ceiling.crack',
  print: {
    safe: ['print.safe.L', 'print.safe.R'],
    warn: ['print.warn.L', 'print.warn.R'],
    danger: ['print.danger.L', 'print.danger.R'],
    plain: ['print.plain.L', 'print.plain.R'],
  },
  badge: 'badge',
  targetRing: 'target.ring',
  targetGlow: 'target.glow',
  pipFull: 'pip.full',
  pipEmpty: 'pip.empty',
  lightSpot: 'light.spot',
  rayBurst: 'ray.burst',
  chest: 'chest',
} as const;

/** Отдельные текстуры (не атласы): запекаются на уровень. */
export const TEX = {
  floor: 'floor',
  walls: 'walls',
  ledge: 'ledge',
  cave: 'cave',
  vignette: 'vignette',
} as const;

export type GemKind = keyof typeof SPR.gem;
export const GEM_KIND_BY_CODE: Record<number, GemKind> = { 2: 'ruby', 3: 'emerald', 4: 'sapphire' };
